web-api-fetch
ramo/js-webapi-projects pull request #1
Opened 2022-11-22 14:27 UTC by ananthmgk

my next 5 web API fetching html

2022-11-23 11:33 UTC, ananthmgk commented
Added bird sound and emoji symbols

2022-11-23 11:34 UTC, ananthmgk commented
bird sound and emoji

2022-11-24 20:24 UTC, ananthmgk commented
created isro with increment item no. and created thirukkural with increment url.

2022-11-25 06:05 UTC, ramo requested changes
Please change the reloading of the windows to refresh the content. Please install prettier plugin and ensure the same formatting throughout the project. 
[](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)

2022-11-25 06:05 UTC, ramo commented on cat-facts.html
> +        <button onClick="window.location.reload()">Next</button>
Instead of windows reload, can we achieve this simply using AJAX?

2022-11-28 16:47 UTC, ananthmgk commented
corrected all the files

2022-12-11 11:43 UTC, ramo approved these changes

2022-12-11 11:44 UTC, merged